# Generated by Django 5.0.1 on 2025-10-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
