# Generated by Django 5.0.1 on 2025-10-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_response_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
    ]
