# Generated by Django 5.0.1 on 2025-09-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_about_us_web_image_welcometo_web_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=300)),
                ('experience', models.PositiveIntegerField()),
                ('specialization', models.TextField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='doctor_photos/')),
                ('registration_no', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('timings', models.CharField(blank=True, max_length=200, null=True)),
                ('social_links', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.ImageField(upload_to='amenitiesimage/')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': '7. Amenities',
            },
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.DeleteModel(
            name='Maharera',
        ),
        migrations.DeleteModel(
            name='Reraaditional',
        ),
        migrations.DeleteModel(
            name='Why_Invest',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='mobile_image',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='logo_2',
        ),
        migrations.RemoveField(
            model_name='unique_selling_proposition',
            name='icone',
        ),
        migrations.RemoveField(
            model_name='unique_selling_proposition',
            name='icone2',
        ),
    ]
