# Generated by Django 5.0.1 on 2025-09-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_about_doctor_service_delete_amenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('value', models.PositiveIntegerField()),
                ('icon_class', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': '7. Service'},
        ),
    ]
