# Generated by Django 5.0.1 on 2025-09-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_stat_alter_service_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='order',
            new_name='Awards',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='value',
            new_name='Departments',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='icon_class',
            new_name='Doctors',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='title',
            new_name='Research_Labs',
        ),
    ]
