# Generated by Django 5.0.1 on 2025-09-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_rename_order_stat_awards_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'verbose_name': 'Stat', 'verbose_name_plural': 'Stat'},
        ),
    ]
