# Generated by Django 5.0.1 on 2025-09-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_stat_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='Doctors',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='Awards',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='Departments',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='Research_Labs',
        ),
        migrations.AddField(
            model_name='stat',
            name='icone',
            field=models.ImageField(default=1, upload_to='doctor_photos/'),
            preserve_default=False,
        ),
    ]
