# Generated by Django 5.0.1 on 2025-09-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_doctors_stat_title_rename_awards_stat_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
