# Generated by Django 5.0.1 on 2025-09-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=150)),
                ('Answer', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
