# Generated by Django 5.0.1 on 2025-09-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_why_choose'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True, help_text='Short tip description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='health_tips/')),
            ],
        ),
    ]
