# Generated by Django 5.0.1 on 2025-09-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_healthtip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Upload client photo (optional)', null=True, upload_to='client_reviews/')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1 to 5 stars')),
                ('review_text', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number shows first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Review',
                'verbose_name_plural': 'Client Reviews',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
