# Generated by Django 5.0.1 on 2025-09-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_clientreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Media',
        ),
    ]
