# Generated by Django 5.0.1 on 2025-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_rename_gallery_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='mission',
            field=models.TextField(blank=True, max_length=5500, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='vision',
            field=models.TextField(blank=True, max_length=5500, null=True),
        ),
    ]
