# Generated by Django 5.0.1 on 2025-09-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_about_us_mission_about_us_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_image', models.ImageField(upload_to='TPAimage/')),
                ('title', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=50)),
            ],
        ),
    ]
